# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 11:15
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_picture',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='play',
            name='image_paths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(max_length=255),
        ),
    ]
