# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApi', '0003_auto_20170328_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fish',
        ),
    ]
