# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-08 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApi', '0005_auto_20170405_1531'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='webusers',
            table='webusers',
        ),
    ]
