# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-08 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApi', '0006_auto_20170408_1420'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actor',
            table='actor',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='play',
            table='play',
        ),
        migrations.AlterModelTable(
            name='play_representation',
            table='play_representation',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='rating',
        ),
        migrations.AlterModelTable(
            name='theater',
            table='theater',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
