# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-24 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApi', '0009_auto_20170409_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='play_representation',
            name='city',
            field=models.CharField(choices=[('Bucharest', 'Bucharest'), ('Alba', 'Alba'), ('Iulia', 'Iulia'), ('Arad', 'Arad'), ('Baia', 'Baia'), ('Mare', 'Mare'), ('Brasov', 'Brasov'), ('Brail', 'Brail'), ('Cluj - Napoca', 'Cluj - Napoca'), ('Constanta', 'Constanta'), ('Craiova', 'Craiova'), ('Deva', 'Deva'), ('Galati', 'Galati'), ('Iasi', 'Iasi'), ('Oradea', 'Oradea'), ('Satu', 'Satu'), ('Mare', 'Mare'), ('Sibiu', 'Sibiu'), ('Sighisoara', 'Sighisoara'), ('Suceava', 'Suceava'), ('Timisoara', 'Timisoara'), ('Targu', 'Targu'), ('Jiu', 'Jiu'), ('Targu', 'Targu'), ('Mures', 'Mures'), ('Tulcea', 'Tulcea'), ('', '')], default='', max_length=255),
        ),
    ]
