# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-24 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileApi', '0010_play_representation_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='trailer_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
